services:
  - type: web
    name: sa-barcode-decoder
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 app_sa:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
